# Generated by Django 4.1.7 on 2023-07-03 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
