# Generated by Django 4.1.7 on 2023-07-04 00:48

import PizzaGang.web.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', PizzaGang.web.managers.AppUserManager()),
            ],
        ),
    ]
