# Generated by Django 4.1.7 on 2023-07-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(upload_to='static/images/pizza/')),
                ('price', models.FloatField()),
                ('is_special', models.BooleanField(blank=True, null=True)),
                ('is_offer', models.BooleanField(blank=True, null=True)),
                ('is_vege', models.BooleanField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
