# Generated by Django 4.1.7 on 2023-07-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='final_price',
            field=models.FloatField(default=0.0),
        ),
    ]
