# Generated by Django 4.1.7 on 2023-07-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_cart_total_price_cartitem_final_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='duplication_count',
            field=models.IntegerField(default=1),
        ),
    ]
