# Generated by Django 4.1.7 on 2023-07-13 14:48

import PizzaGang.main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(default=0.0, validators=[PizzaGang.main.validators.validate_positive]),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0.0, validators=[PizzaGang.main.validators.validate_positive]),
        ),
    ]
