# Generated by Django 4.1.7 on 2023-04-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ingredients', models.TextField()),
                ('size', models.CharField(choices=[('FR', 'Personal'), ('SO', 'Small'), ('JR', 'Medium'), ('SR', 'Large')], max_length=30)),
                ('is_offer', models.BooleanField()),
            ],
        ),
    ]
