# Generated by Django 4.1.7 on 2023-04-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='is_offer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(blank=True, choices=[('FR', 'Personal'), ('SO', 'Small'), ('JR', 'Medium'), ('SR', 'Large')], max_length=30, null=True),
        ),
    ]
