# Generated by Django 4.1.7 on 2023-04-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_pizza_is_offer_alter_pizza_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
