# Generated by Django 4.1.7 on 2023-04-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_pizza_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(blank=True, choices=[('PE', 'Personal'), ('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], max_length=30, null=True),
        ),
    ]
