# Generated by Django 4.1.7 on 2023-05-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_pizza_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='is_offer',
            new_name='is_special',
        ),
        migrations.AddField(
            model_name='pizza',
            name='is_vege',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
