# Generated by Django 4.1.7 on 2023-05-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_rename_is_offer_pizza_is_special_pizza_is_vege'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='is_offer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
