# Generated by Django 4.1.7 on 2023-05-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_pizza_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
