# Generated by Django 4.1.7 on 2023-05-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_profile_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(default='PE', max_length=50),
        ),
    ]
