# Generated by Django 4.1.7 on 2023-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_alter_cart_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(default='ME', max_length=50),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(blank=True, choices=[('PE', 'Personal'), ('SM', 'Small'), ('ME', 'Medium'), ('LA', 'Large')], default='ME', max_length=30, null=True),
        ),
    ]
