# Generated by Django 4.1.7 on 2023-05-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_cart_size_alter_pizza_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to='static/pictures/profile/'),
        ),
    ]
