# Generated by Django 4.1.7 on 2023-05-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
