# Generated by Django 4.1.3 on 2022-12-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(null=True),
        ),
    ]
