# Generated by Django 4.1.4 on 2022-12-06 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(null=True)),
                ('salary', models.IntegerField(null=True)),
            ],
        ),
    ]
