# Generated by Django 4.1.4 on 2022-12-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='works_full_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
