# Generated by Django 4.1.4 on 2022-12-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_employees_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='project',
            field=models.ManyToManyField(to='web.projects'),
        ),
    ]
