# Generated by Django 4.1.4 on 2022-12-09 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_projects_employees_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['age']},
        ),
    ]
