# Generated by Django 4.1.4 on 2022-12-09 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_employees_options_employees_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='project',
            field=models.ManyToManyField(to='web.projects'),
        ),
    ]
