# Generated by Django 4.1.7 on 2023-04-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(choices=[('sm', 'Small'), ('me', 'Medium'), ('la', 'Large')], default='Medium', max_length=30),
        ),
    ]
