# Generated by Django 4.1.7 on 2023-04-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
    ]
