# Generated by Django 4.1.4 on 2022-12-07 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.departments'),
        ),
    ]
