# Generated by Django 4.1.4 on 2022-12-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_employees_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['age', 'pk']},
        ),
        migrations.AddField(
            model_name='employees',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='web.projects'),
        ),
    ]
