# Generated by Django 4.1.4 on 2022-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_employees_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departments',
            options={'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['age', 'pk'], 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='departments',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
