# Generated by Django 4.1.4 on 2022-12-17 16:44

from django.db import migrations, models
import forms_two.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0, validators=[forms_two.web.validators.less_than_10, forms_two.web.validators.more_than_65]),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=22, validators=[forms_two.web.validators.is_upper]),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=22, validators=[forms_two.web.validators.is_upper]),
        ),
    ]
